modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="dark"
version="1.1.7"
displayName="Dark Dimension Mod"
credits="Adds a new Dimension the dark dimmension"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Wolfalpha360"

[[dependencies.dark]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




